env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - id: cheat-darwin-amd64
    ldflags: -s -w -X github.com/darrikonn/cheat.Version={{.Version}} -X github.com/darrikonn/cheat.BuildDate={{.Date}} -X github.com/darrikonn/cheat.CommitHash={{ .ShortCommit }}
    binary: cheat
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    main: ./cheat.go
    goos:
      - darwin
    goarch:
      - amd64
  - id: cheat-linux-amd64
    ldflags: -s -w -X github.com/darrikonn/cheat.Version={{.Version}} -X github.com/darrikonn/cheat.BuildDate={{.Date}} -X github.com/darrikonn/cheat.CommitHash={{ .ShortCommit }}
    binary: cheat
    env:
      - CGO_ENABLED=1
    main: ./cheat.go
    goos:
      - linux
    goarch:
      - amd64
  - id: cheat-windows-amd64
    ldflags: -s -w -X github.com/darrikonn/cheat.Version={{.Version}} -X github.com/darrikonn/cheat.BuildDate={{.Date}} -X github.com/darrikonn/cheat.CommitHash={{ .ShortCommit }}
    binary: cheat
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    main: ./cheat.go
    goos:
      - windows
    goarch:
      - amd64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{.ProjectName}}-v{{.Version}}-{{.Os}}-{{.Arch}}'
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - Merge pull request
      - Merge branch
brew:
  github:
    owner: darrikonn
    name: homebrew-formulae
  homepage: https://github.com/darrikonn/cheat
  description: Secure, email-like messaging for blockchain addresses and accounts
  test: |
    system "#{bin}/cheat -v"
