# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: cheat
before:
  hooks:
    - go mod tidy
      # - xgo github.com/mattn/go-sqlite3
      # - go generate ./...
builds:
  -
    main: ./cheat.go
    binary: cheat
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
        # - CC=gcc
        # - CXX=clang++
    asmflags:
      - -D mysymbol
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
      - ./dontoptimizeme=-N
    # ldflags:
    #  - -s -w -X main.build={{.Version}}
    #  - ./usemsan=-msan
    # goos:
    #   - linux
    #   - darwin
    goarch:
      - amd64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
brews:
  -
    name: cheat
    github:
      owner: darrikonn
      name: homebrew-tap
    url_template: "https://github.com/darrikonn/cheat/releases/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    homepage: "https://github.com/darrikonn/cheat"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      windows: Windows
      amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
  algorithm: sha256
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
