version: 2.1
description: |
  Installs dev and packaging dependencies and builds cli


workflows:
  version: 2.1
  cheat:
    jobs:
      - lint_and_build:
          context: "latest"
      - lint_and_build:
          context: "1.13"
      - lint_and_build:
          context: "1.12"
      - lint_and_build:
          context: "1.11"
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

executors:
  go:
    description: Go build image
    parameters:
      version:
        description: Go version to use
        type: string
        default: "latest"
    docker:
      - image: circleci/golang:<<parameters.version>>

references:
  workspace: &workspace
    /go/src/github.com/spf13/cobra
  lint: &lint
    run:
      name: "Lint"
      command: make lint
  build: &build
    run:
      name: "build"
      command: go build

commands:
  setup:
    description: |
      Installs all dependencies (dev as well)
    steps:
      - run:
          name: "Install requirements"
          command: make requirements
      - run:
          name: "Install dev requirements"
          command: make dev-requirements

jobs:
  lint_and_build:
    executor:
      name: go
      version: "$GO_VERSION"
    working_directory: *workspace
    steps:
      - checkout
      - setup
      - *lint
      - *build
  release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
