version: 2.1
description: |
  Installs dev and packaging dependencies and builds cli

workflows:
  version: 2.1
  cheat:
    jobs:
      - lint_build_test:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - lint_build_test
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

executors:
  xcgo:
    description: GoReleaser xcgo build image
    parameters:
      version:
        description: Go version to use
        type: string
        default: 'latest'
    docker:
      - image: darrikonn/goreleaser-xcgo:<<parameters.version>>
  go:
    description: Go build image
    parameters:
      version:
        description: Go version to use
        type: string
        default: 'latest'
    docker:
      - image: circleci/golang:<<parameters.version>>

references:
  workspace: &workspace
    /go/src/github.com/darrikonn/cobra
  lint: &lint
  build: &build

jobs:
  lint_build_test:
    executor:
      name: go
      version: '1.13'
    working_directory: *workspace
    steps:
      - checkout
      - run:
          name: 'Install requirements'
          command: make requirements
      - run:
          name: 'Install dev requirements'
          command: make dev-requirements
      - run:
          name: 'Lint'
          command: make lint
      - run:
          name: 'Build'
          command: go build
      - run:
          name: 'Test'
          command: cheat

  release:
    executor:
      name: xcgo
    steps:
      - checkout
      - run:
          name: 'Create releases with GoReleaser'
          command: goreleaser --rm-dist
