version: 2.1
description: |
  Installs dev and packaging dependencies and builds cli

workflows:
  version: 2.1
  cheat:
    jobs:
      - lint_and_build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - lint_and_build
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

executors:
  go:
    description: Go build image
    parameters:
      version:
        description: Go version to use
        type: string
        default: 'latest'
    docker:
      - image: circleci/golang:<<parameters.version>>
    environment: 
      LATEST: true
      GO111MODULE: on

references:
  workspace: &workspace
    /go/src/github.com/darrikonn/cobra
  lint: &lint
    run:
      name: 'Lint'
      command: make lint
  build: &build
    run:
      name: 'build'
      command: go build

jobs:
  lint_and_build:
    executor:
      name: go
      version: '1.13'
    working_directory: *workspace
    steps:
      - checkout
      - run:
          name: 'Install requirements'
          command: make requirements
      - run:
          name: 'Install dev requirements'
          command: make dev-requirements
      - *lint
      - *build

  release:
    executor:
      name: go
      version: '1.13'
    steps:
      - checkout
      - run:
          name: 'Create releases with GoReleaser'
          command: |
            docker run -e GITHUB_TOKEN=$GITHUB_TOKEN --rm --privileged -v $CIRCLE_WORKING_DIRECTORY:/go/src/github.com/darrikonn/cheat -v /var/run/docker.sock:/var/run/docker.sock -w /go/src/github.com/darrikonn/cheat darrikonn/goreleaser-xcgo goreleaser --rm-dist
