version: 2.1
description: |
  Installs dev and packaging dependencies and builds cli

workflows:
  version: 2.1
  cheat:
    jobs:
      - go-latest
      - go-one-thirteen
      - go-one-twelve
      - go-one-eleven
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

executors:
  go:
    description: Go build image
    parameters:
      version:
        description: Go version to use
        type: string
        default: 'latest'
    docker:
      - image: circleci/golang:<<parameters.version>>

references:
  workspace: &workspace /go/src/github.com/spf13/cobra
  lint: &lint
    run:
      name: 'Lint'
      command: make lint
  build: &build
    run:
      name: 'build'
      command: go build

commands:
  lint_and_build:
    description: |
      Installs all dependencies (dev as well)
    steps:
      - checkout
      - run:
          name: 'Install requirements'
          command: make requirements
      - run:
          name: 'Install dev requirements'
          command: make dev-requirements
      - *lint
      - *build

jobs:
  go-latest:
    executor:
      name: go
      version: '1.13'
    working_directory: *workspace
    steps:
      - lint_and_build
  go-one-thirteen:
    executor:
      name: go
      version: '1.13'
    working_directory: *workspace
    steps:
      - lint_and_build
  go-one-twelve:
    executor:
      name: go
      version: '1.13'
    working_directory: *workspace
    steps:
      - lint_and_build
  go-one-eleven:
    executor:
      name: go
      version: '1.13'
    working_directory: *workspace
    steps:
      - lint_and_build

  release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
